name=input('Hello! Please type your name here: ')
dob=input('date of birth(MM/DD/YYYY): ')
age=input('age: ')
email=input('email address: ')
language=input('known languages: ')
occupation=input('occupation: ')

print('\n')
print('Hello!',name)
print('Your biodata:')
print('\tDOB:', dob)
print('\tAGE:',age)
print('\tEMAIL:',email)
print('\tLANGUAGES:',language)
print('\tOCCUPATION:',occupation)